### ISSUE TITLE
User received security warning on docker-machine page

### ISSUE THREAD

**Issue by moxiegirl** [docker/docs-base#107]
just to let you know that accessing https://docs.docker.com/machine/install-machine/ with chrome mac gave me this

![image](https://cloud.githubusercontent.com/assets/1347209/8657839/db3c0d76-2954-11e5-9dc2-024bdfa35d72.png)

**Comment by thaJeztah** [comment]
@moxiegirl https://www.google.com/safebrowsing/diagnostic?site=docs.docker.com

**Comment by thaJeztah** [comment]
The report is not very helpful though; doesn't say which pages were marked "unsafe" and why (have had some false positives with Google in the past, so it could be just a bogus warning)

**Comment by moxiegirl** [comment]
@thaJeztah I'm working with our internal security team on this.

**Comment by moxiegirl** [comment]
https://github.com/docker/machine/pull/1519 fixed this

**Comment by thaJeztah** [comment]
sigh... silly reason for blocking

glad it's resolved then
