### ISSUE TITLE
update link of the whale logo in the global menu

### ISSUE THREAD

**Issue by bettyjunod** [docker/docs-base#109]
currently it goes to docs.docker.com but can it redirect to www.docker.com?

**Comment by thaJeztah** [comment]
Looks like a dup of https://github.com/docker/docs-base/issues/51 (and https://github.com/docker/docs-base/issues/52)

**Comment by thaJeztah** [comment]
Oh! Forgot I have write access here

Thanks for reporting @bettyjunod, I'm going to close this issue as a dup of https://github.com/docker/docs-base/issues/52, but feel free to comment (or harass me on Twitter) if you think I closed this by mistake :smile:
