### ISSUE TITLE
windows IE cant hover menu

### ISSUE THREAD

**Issue by jfrazelle** [docker/docs-base#11]
on a windows PC I cannot hover the menu items in the menubar for the subitems

**Comment by ahmetalpbalkan** [comment]
browser info?

**Comment by thaJeztah** [comment]
http://www.whatsmybrowser.org

**Comment by moxiegirl** [comment]
This was on the old site.  I'll have the scripters test on all supported browsers. https://github.com/docker/docs-base/issues/73
