### ISSUE TITLE
Links broken for Remote API docs

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docs-base#122]
http://docs.docker.com/reference/api/docker_remote_api/#full-documentation
 
I am clicking on the following:

> ![image](https://cloud.githubusercontent.com/assets/159209/9151725/15f56dd2-3dc2-11e5-8945-d0df62a17e00.png)

that's linked to http://docs.docker.com/reference/reference/reference/api/docker_remote_api_v1.19/ however that redirects to http://docs.docker.com/index.html 

All other API versions are broken, too.

**Comment by dnephin** [comment]
Looks like this is fixed now. I think it can be closed.

**Comment by vdemeester** [comment]
ah feels like it yeah, closing :wink: 
Thanks @dnephin
