### ISSUE TITLE
404 for base images page

### ISSUE THREAD

**Issue by bettyjunod** [docker/docs-base#129]
https://docs.docker.com/articles/baseimages/

when I click on "base image" highlighted at the top of the page in orange, I am redirected to this page

https://docs.docker.com/terms/image/#base-image

which when you navigate to it results in a 404 not found.

**Comment by thaJeztah** [comment]
Thanks for reporting! this is something that has  to be fixed in the docker repository (that's where that page lives); for reference, a similar issue was just fixed in this PR: https://github.com/docker/docker/pull/15451

**Comment by thaJeztah** [comment]
Actually, I think this will be covered by https://github.com/docker/docker/issues/15530

I'll close this issue, otherwise I'll forget ;-) thanks Betty!
