### ISSUE TITLE
broken link - understanding-docker page

### ISSUE THREAD

**Issue by bettyjunod** [docker/docs-base#139]
https://docs.docker.com/misc/introduction/understanding-docker.md

**Comment by aditirajagopal** [comment]
https://docs.docker.com/misc/ ---> https://docs.docker.com/engine/misc/

which leads to https://docs.docker.com/engine/introduction/understanding-docker/ 

How did you get to that page in the first place?

**Comment by thaJeztah** [comment]
I suspect that link is from before the tool-changes we made; before those changes, links to `something.md` were not automatically converted to the right URL.

Looks like this link is fixed, so I close this issue :)
