### ISSUE TITLE
"docker ps" docs missing formatting option: .Names

### ISSUE THREAD

**Issue by dlopuch** [docker/docs-base#151]
https://docs.docker.com/reference/commandline/ps/

The "Formatting" section lists all valid options that you could put into a custom formatting template.  It appears to be missing the `.Names` placeholder (which is included in the default ps output).

**Comment by thaJeztah** [comment]
Thanks for reporting @dlopuch, it looks like this has been fixed in this PR: https://github.com/docker/docker/pull/16153, but those changes haven't been published yet on the website.

I'll close this issue, because it has been resolved, but thanks again for reporting! :metal:
