### ISSUE TITLE
Add Volume Plugin : docker-volume-netshare

### ISSUE THREAD

**Issue by gondor** [docker/docs-base#152]
I'm not sure if this is the appropriate place to file this but I've contributed a volume driver we use in our production clusters which handles mounting NFS, AWS EFS & CIFS mount points within containers.

On the https://docs.docker.com/extend/plugins/ page would it be possible to add:

The [Netshare](https://github.com/gondor/docker-volume-netshare) plugin is a plugin that provides support for NFS 3/4, EFS and CIFS volume management for docker.

**Comment by SvenDowideit** [comment]
@gondor this would be something you'd do in a PR on the https://github.com/docker/docker repository :)

**Comment by gondor** [comment]
Thank you :)
