### ISSUE TITLE
Need to make a 404 page that works

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docs-base#155]
`public/404.html` is an empty file :(

and with the GH-linking version of the site, the bucket meta-data is using the 404.html file.

we could either make a markdown file, which gets rendered using the hugo theme (i prefer that atm) or we can add a full html file as is now - but that will add to the updating workload for theme changes.

**Comment by SvenDowideit** [comment]
or ... mary suggested hugo has a 404 layout - so i looked: https://gohugo.io/templates/404/

**Comment by dnephin** [comment]
I think this is done, yes?

**Comment by SvenDowideit** [comment]
agreed., closing.
