### ISSUE TITLE
Docker Hub API link broken

### ISSUE THREAD

**Issue by bfirsh** [docker/docs-base#187]
https://docs.docker.com/engine/reference/api/docker-io_api/

The link on this page links to itself. It should link to http://docs.docker.com/v1.7/docker/reference/api/docker-io_api/

**Comment by thaJeztah** [comment]
This is already fixed in master, but not yet online; see https://github.com/docker/docker/pull/18341

@moxiegirl if you're doing an update to docs.docker.com, perhaps you can cherry-pick that one?

**Comment by moxiegirl** [comment]
belongs in docker/docker
