### ISSUE TITLE
Double dashes are rendered as en dash

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docs-base#189]
If the titles have `--` in them, they're converted to typographic en dash “–” character, which wouldn't work if it is copy-pasted into terminal. I think it's a problem.

> ![image](https://cloud.githubusercontent.com/assets/159209/11969178/f4b1c520-a8ca-11e5-8b70-7d1014a4d9f9.png)

or

> ![image](https://cloud.githubusercontent.com/assets/159209/11969185/f5b5fc34-a8ca-11e5-91ff-854923295193.png)

**Comment by thaJeztah** [comment]
Oh, hm. I think we previously had those in back-tics, but that was really "noisy" from a layout perspective. I wonder if it's configurable in Hugo to not replace those.

**Comment by thaJeztah** [comment]
Looks like theres a "smartDashes" (and "smartypants") option; https://gohugo.io/overview/configuration/

**Comment by thaJeztah** [comment]
Hm, weird. the "smartDashes" option doesn't work. I can disable "smartypants", but that will also disable curly quotes :cry: Could be because we currently use a custom build, because https://github.com/spf13/hugo/pull/1398 is not yet merged upstream

**Comment by thaJeztah** [comment]
Yup, that looks to be the problem; this change  isn't in our branch https://github.com/docker/hugo/blob/1bad78ea394170dfcc8e7d463503057fc4514007/helpers/content.go#L43-L53

ping @SvenDowideit would you be able to rebase your/our fork and tag a "test-3" version?

**Comment by SvenDowideit** [comment]
back from holidays, taking a look :)

**Comment by SvenDowideit** [comment]
@moxiegirl LGTM
