### ISSUE TITLE
"tags" metadata surrounding braces

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docs-base#216]
markdown:
```
 <!--[metadata]>
 ...
 keywords = ["machine, Microsoft Azure, driver"]
```

is translated to HTML:

        <meta name="keywords" content="[machine, Microsoft Azure, driver]">

Surrounding braces seem a bit wrong.

**Comment by thaJeztah** [comment]
Yes, I noticed this a while back; I think we even discussed if we actually still need keywords/description for indexing.

**Comment by SvenDowideit** [comment]
i've resolved this in the dockercon 2016 theme :)

**Comment by thaJeztah** [comment]
@SvenDowideit does the theme now accept both the (wrong) "string" notation, and actual arrays?
