### ISSUE TITLE
Improve documentation contents

### ISSUE THREAD

**Issue by andig** [docker/docs-base#294]
I've found https://docs.docker.com/swarm/install-manual/ to be confusing- where can I raise such issues?

**Comment by thaJeztah** [comment]
@andig that documentation is part of the Swarm repository; https://github.com/docker/swarm. You can open an issue in that issue tracker.

Also note that those docs are for "Swarm", not the new "Swarm mode" that will be introduced in the upcoming 1.12 release of docker. Docs for that can be found here; https://docs.docker.com/engine/swarm/ (but are still WIP)

**Comment by thaJeztah** [comment]
I'll close this issue here, but feel free to continue the discussion
