### ISSUE TITLE
un-htmlencoded ampersand & in  fonts/LigatureSymbols/index.html

### ISSUE THREAD

**Issue by lloydde** [docker/docs-base#37]
Doesn't get any more trivial bug than this, but I was running some html validation on all repos I had checked and found:
~~~
$ find . -name '*.html' -exec ag -H ' & ' {} \;
theme/mkdocs/fonts/LigatureSymbols/index.html
1258:  <h2>HTML & CSS</h2>
1259:  <p>Please copy & paste this code to your HTML file or Stylesheet.</p>
~~~

Looks like this is already resolved upstream. Feel free to close "won't fix".

**Comment by moxiegirl** [comment]
@lloydde The specific file you refer to is part of our old documentation tool set. We just recently switched to a new tool set. So, that file should disappear entirely from our systems shortly.

Thanks for taking the time to file the issue. Much appreciated.
