### ISSUE TITLE
Registry docs home not accesible from UI navigation

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docs-base#39]
https://docs.docker.com/registry/

this page is no longer accessible from sidebar by clicking on these links. I had to write this from memory.

![image](https://cloud.githubusercontent.com/assets/159209/8245503/46791112-15e4-11e5-80de-7e4f7bf599bb.png)

**Comment by ahmetalpbalkan** [comment]
Also those 3 links listed under "Registry" are the least important links. 

At the end of this page https://docs.docker.com/registry/ there are far more important links that probably should go to the sidebar.

**Comment by moxiegirl** [comment]
@ahmetalpbalkan Decisions about how to structure the registry documentation are made in the https://github.com/docker/distribution project. Can you file your issues with Registry docs there in the future? I'll create a pointer back to this and close this one.

**Comment by ahmetalpbalkan** [comment]
I am sent here from there. :-)

**Comment by moxiegirl** [comment]
@ahmetalpbalkan realllly. Okay...I'll talk to them and leave this open. BTW, your first issue, I can't repro

![image](https://cloud.githubusercontent.com/assets/1347209/8246378/a458681a-15f2-11e5-8fd0-3f86408d34e0.png)

**Comment by ahmetalpbalkan** [comment]
oh I was looking at the wrong place for registry docs...
