### ISSUE TITLE
Code block styling is not good

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docs-base#41]
Saw this here https://docs.docker.com/registry/configuration/

I think a code block probably should be rendered with a full width background color or something like that. Looks like a styling mistake?

![image](https://cloud.githubusercontent.com/assets/159209/8245543/a6ae88fa-15e4-11e5-8965-ef21291876c9.png)

**Comment by duglin** [comment]
noticed this too but was told things were still "in flux" so I was holding off before opening up issues/PRs.

**Comment by bfirsh** [comment]
Judging by http://docs.docker.com/compose/ there seems to be one style that works, but one that doesn't... perhaps we're using two different methods to do code blocks.

**Comment by ahmetalpbalkan** [comment]
Yep looks like there's a mixed mode:

![image](https://cloud.githubusercontent.com/assets/159209/8263099/b1d7a2fe-168c-11e5-91bf-e7f172791ca0.png)

Three backticks render as a `<pre>` code block:

![image](https://cloud.githubusercontent.com/assets/159209/8263135/eea5035c-168c-11e5-9afb-0bc34286609c.png)

However four space indented blocks are rendered as `<code>`:

![image](https://cloud.githubusercontent.com/assets/159209/8263163/0af9035a-168d-11e5-8021-88ea8cf04b95.png)


It's most likely something wrong with the markdown parser.

**Comment by moxiegirl** [comment]
@bfirsh is correct. GitHub-Flavored-Markdown supports the ``` method. Hugo doesn't handle GFM. Hugo delegate all its markdown rendering to Blackfriday (a Go lib). https://github.com/russross/blackfriday34
So, they render as lines.  Using indent is the correct method.  The problem is in the source file.

We are using https://highlightjs.org/ which supports a lot of formats including Dockerfiles.
