### ISSUE TITLE
Daemon vs detached terms in docker-compose

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docs-base#43]
Here: http://docs.docker.com/compose/

> ![image](https://cloud.githubusercontent.com/assets/159209/8247186/c543497e-1600-11e5-8ce1-27921a210b40.png)

it says "daemon mode" to the -d flag.

in the cli reference it refers to it as "detached mode":

> ![image](https://cloud.githubusercontent.com/assets/159209/8247194/db0dfcae-1600-11e5-9e82-d58756df2b04.png)

I believe the correct and accurate one is "detached mode".

**Comment by moxiegirl** [comment]
@ahmetalpbalkan This should be filed in the docker/compose project. It has to do with content not with layout on docs.docker.com. Feel free to reopen if you disagree.
