### ISSUE TITLE
Diagrams fail to load on networking article

### ISSUE THREAD

**Issue by bberberov** [docker/docs-base#45]
There were diagrams on this page ( https://docs.docker.com/articles/networking/ ) before, but they fail to load now.  According to FF's developer tools, they are 404.  Maybe you are just rewriting the article and don't need them, but they were helpful in the old version.

**Comment by moxiegirl** [comment]
Thanks @bberberov  for the heads up. We'll get on it.

**Comment by bberberov** [comment]
There is probably more to it.  Look here: https://docs.docker.com/reference/builder/

```HTML
<blockquote>
<p><strong>Note</strong>:
<code>EXPOSE</code> doesn’t define which ports can be exposed to the host or make ports
accessible from the host by default. To expose ports to the host, at runtime,
<a href="/reference/reference/reference/userguide/dockerlinks">use the <code>-p</code> flag</a> or
<a href="/reference/reference/reference/reference/run/#expose-incoming-ports">the -P flag</a>.</p>
</blockquote>
```

I don't think that "reference" is four levels down.

**Comment by moxiegirl** [comment]
@bberberov I think what is happening is you are seeing old material.  We are having issues with redirect. I'll update later today.  Thanks!

**Comment by bberberov** [comment]
Something changed.  Now I am seeing 301s instead of 404s, but the images are not loading.  I'll just show you.

![snapshot19](https://cloud.githubusercontent.com/assets/7432115/8269438/bec3bcaa-176d-11e5-9503-9b48210899dd.png)

Let me know if you need any other debugging information.

**Comment by moxiegirl** [comment]
@bberberov I've been debugging this today.  I'm very much certain this is related to our build scripts. I'm testing on a staging system presently.   Plan to have this sorted today.

**Comment by moxiegirl** [comment]
@bberberov I think I found the issue and solved it. Can you confirm when you get a chance? This is what I see:
![image](https://cloud.githubusercontent.com/assets/1347209/8270094/c4cde3a0-1781-11e5-93b6-e2339df64802.png)

**Comment by bberberov** [comment]
@moxiegirl  Yes.  It appears fixed.
