### ISSUE TITLE
Headers transform two dashes (--) into &mdash; which breaks search

### ISSUE THREAD

**Issue by moxiegirl** [docker/docs-base#66]
Laura @rheinwein commented this developer works with Jerome

**Comment by moxiegirl** [comment]
@rheinwein Can you provide me a screen capture of what you are seeing?

**Comment by rheinwein** [comment]
This happens for every header that includes `--`
![image](https://cloud.githubusercontent.com/assets/775634/8450159/52812438-1fd8-11e5-8630-0d87da34bf37.png)

`<h2 id="pid-settings-pid">PID settings (–pid)</h2>`

Unsure if it's the parser or something else, as it's correct in the original md file: https://github.com/docker/docker/blob/master/docs/reference/run.md#pid-settings---pid

**Comment by moxiegirl** [comment]
Thanks for the clarification @rheinwein . We'll look into it and see what we can do.

**Comment by dnephin** [comment]
I think this was fixed by #190

**Comment by thaJeztah** [comment]
Oh, yes, looks like a dup of https://github.com/docker/docs-base/issues/189. Closing this, because it's fixed now;

<img width="646" alt="screen shot 2016-02-11 at 11 58 50" src="https://cloud.githubusercontent.com/assets/1804568/12974780/deb32d5e-d0b6-11e5-8730-837970747ecb.png">
