### ISSUE TITLE
Leave white space between top of footer wave and bottom of page.

### ISSUE THREAD

**Issue by moxiegirl** [docker/docs-base#75]
Need some space between the top of the wave and the end of page.

![image](https://cloud.githubusercontent.com/assets/1347209/8413949/448d3596-1e49-11e5-881a-a0299ac2f141.png)

**Comment by ClemMakesApps** [comment]
What page was this on? I'm unable to find this screenshot example.

**Comment by FSHA** [comment]
The wave asset no longer exists. Not sure if this is still an issue, now that we have removed that UI element.

**Comment by thaJeztah** [comment]
Let's close it
