### ISSUE TITLE
Governance link 404

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docs-base#79]
Landed to https://www.docker.com/governance from a search engine 

The page probably 404s but prints no text to the screen:

>  ![image](https://cloud.githubusercontent.com/assets/159209/8359757/32e0edd0-1b1d-11e5-99d0-b400fe8e7f39.jpg)

**Comment by moxiegirl** [comment]
Hi @ahmetalpbalkan that one is for the www project.  They don't have a GitHub project. So, I'll let them know about this.  Thanks.
