### ISSUE TITLE
Indentation in code blocks

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docs-base#89]
At this page:
http://docs.docker.com/registry/configuration/

the current design **loses the indentation in the code block** makes it impossible to read from the documentation:
> ![image](https://cloud.githubusercontent.com/assets/159209/8395166/e656baea-1d14-11e5-9c39-0b2a83514a3b.png)

**Comment by thaJeztah** [comment]
Looks like another issue with GitHub flavoured Markdown;

https://raw.githubusercontent.com/docker/distribution/master/docs/configuration.md

That files uses the "fenced" notation (````) for the code blocks, which isn't supported properly (yet) by the tooling. This results in *each line* being rendered as a separate code-block, loosing the indentation.

Wondering if we can (as a stop-gap solution) pre-process the Markdown, replacing those blocks with a HTML `<pre>` or similar

**Comment by moxiegirl** [comment]
@thaJeztah I'd rather fix the source than instrument around it.  Let's leave this open. I'll need to go page-by-page for this stuff.

**Comment by thaJeztah** [comment]
Agreed, was a bit worried that not all teams agree with having to change because the tooling doesn't support it :/

**Comment by ahmetalpbalkan** [comment]
The markdown library you guys are using is not using the "github flavored markdown" and new people writing docs will keep hitting the issue. Simply because three backticks is a common enough way to describe code blocks in GFM.

Let's say I'm creating a new pull request, I will see the preview of the docs I'm writing on GitHub and I will assume you guys are using the same, and if the reviewer misses the three-backticks being used, the docs will go live as broken.

I suggest you to change the library rather than updating the docs.

**Comment by moxiegirl** [comment]
@ahmetalpbalkan GitHub does support the indentation and so does our generation tool.  The vast majority of our documentation uses the indents.  It was as we added the sub projects that the tics became an issue; so tradition and training and avoid much of these problems.

Agreed though, we need to make a decision regarding full on support of GFM. They impact both our public repos and our private ones. Decisions in this area also resource dependent as they impact open source contributors, documentation management, and staffing. Those discussions are kicking off internally right now. Of course, we will surface them as soon as I can.

**Comment by stevvooe** [comment]
@ahmetalpbalkan I agree with you on the GFM sentiment. We use it every day and it should carry over to the documentation.

**Comment by berlincount** [comment]
In plenty of cases this messes with the documentation in a way to make it unusable for users. Is there a plan to prioritize this comparatively easy to fix problem?

**Comment by moxiegirl** [comment]
@berlincount this was caused by a miscoding in the Markdown. It was fixed recently in the source and will disappear in the next release cycle.

**Comment by berlincount** [comment]
@moxiegirl hmm - a problem in the markdown or a problem in the markdown parser? I think the code should be generous about what it accepts, especially as GitHub Markdown can be considered the primary Markdown flavor these days.

When will the next release be? How often are the docs regenerated? There was a relevant fix to the documentation that hasn't made it to the page, for example ... Thanks! :)

**Comment by moxiegirl** [comment]
@berlincount  Our code highlighter, highlight.js, doesn't support yaml.  This is fixed by removing the "yaml" designation from the markdown.

Each project is different -- some like to release doc updates between official releases some don't.  This page is in the distribution project and they sometimes do.  Their release cycle is here: https://github.com/docker/distribution/wiki

**Comment by stevvooe** [comment]
@berlincount @moxiegirl If you look at http://docs.docker.com/registry/configuration/, a `pre` element is correctly generated, but it is rendered oddly. This is actually a bug in the css, rather than source file. Fenced code blocks ("backticks") should be supported in the documentation pipeline.

**Comment by moxiegirl** [comment]
@stevvooe

**Comment by ahmetalpbalkan** [comment]
fixed now
