### ISSUE TITLE
TOC doesn't show up in Docker Compose docs

### ISSUE THREAD

**Issue by jpetazzo** [docker/docs-base#9]
In the Docker Compose documentation, the TOC shows up in the document:

- Installing Compose
- Command line reference
- Yaml file reference
- Compose environment variables
- Compose command line completion

But doesn't show up on the left side. I don't know if this is a templating issue or a content issue, so feel free to bounce me back to the appropriate place if needed!

**Comment by moxiegirl** [comment]
Helpful to have a URL @jpetazzo On this page:

http://docs.docker.com/compose/
http://docs.docker.com/compose/install/

I'm seeing both left hand navs in Chrome:

![image](https://cloud.githubusercontent.com/assets/1347209/7101824/a18c1e50-e01f-11e4-979e-25e36015d69f.png)

**Comment by jpetazzo** [comment]
Oh my bad, I thought I had copy-pasted the URL :cry: 

I was expecting links to the compose command-line reference and YAML file syntax to be available easily, e.g. in the nav bar, instead of having to scroll down in the document... Or am I missing something?

**Comment by moxiegirl** [comment]
@jpetazzo I don't know what was intended with those Let's ping @fredlf @SvenDowideit who put them together.

**Comment by fredlf** [comment]
@jpetazzo Those docs are all linked up in the top menus, e.g., Yaml reference is under "Reference", "install" is under "Installation", etc. 

It's not ideal, that's why I added the menu at the bottom of the page as well. When we re-architect the site in June it will be more logical.

**Comment by jpetazzo** [comment]
Ohh, right. I had checked that nav bar, but my eyes stopped scanning at "Dockerfile" because I thought it was the top-level menu for the docs, and I wasn't expecting to see more detailed compose stuff in there.  Hmmm... IMVHO we should have the "local TOC" to the left as well, but I'm no UX expert (just a ref wanderer :-) )

**Comment by fredlf** [comment]
The last mockups I saw for the new site template have a left-hand ToC. I'll be sure to pass on your user-testing feedback to the UX guys! :-)

Not all who wander... etc.

**Comment by jpetazzo** [comment]
<3

Thanks!

**Comment by rheinwein** [comment]
Want to reopen discussion on this issue based on the docs site redesign -- will the granular sidebar return? Especially for articles like `run` and `Dockerfile`, a detailed sidebar was incredibly useful when searching for specific info.

![image](https://cloud.githubusercontent.com/assets/775634/8267991/eefe1678-173a-11e5-91c3-f184093a3d3a.png)

Now, the only option is to cmd+f, which works of course -- just a bit clunky.

**Comment by moxiegirl** [comment]
@rheinwein @jpetazzo  Yes, it will.  We will be adding a page content feature shortly that will allow you to jump down the page. There wasn't time for us to implement that before the initial release.  

There are also just general problems with the length of our reference pages.  The plan is to break out each command into its own subpage. The feedback I'm getting is that this would be good thing. I'd love to know your thoughts?

@fredlf I'm not aware of any plans to redesign  docs.docker.com in what remains of June. We are going to be working with the scripting team to upgrade the features on the Hugo layout.  And we are planning on implementing a common header/footer across all our sites. 

Thanks for the feedback...I'll keep this open @rheinwein until we have it all complete.

**Comment by moxiegirl** [comment]
A mini-toc is available now on each page.  
![image](https://cloud.githubusercontent.com/assets/1347209/8411455/e5c8fbb8-1e38-11e5-9ee2-15d023714d63.png)

Compose YAML reference is here with mini toc as well.

![image](https://cloud.githubusercontent.com/assets/1347209/8411488/069a8b36-1e39-11e5-92af-a2f5f9b20da9.png)
