### ISSUE TITLE
Anchor Links in headers

### ISSUE THREAD

**Issue by huslage** [docker/docs-base#98]
![Screenshot](https://www.dropbox.com/s/8rtdqllcoacocpe/Screenshot%202015-07-01%2014.48.34.png?dl=1)

The headers need to have copyable URL links so that it's easy to share deep-links from within the context of the document. Right now you have to scroll up to the mini-ToC to get them.

I had to inspect the source code to generate this URL:

https://docs.docker.com/docker-trusted-registry/configuration/#ldap-authentication

**Comment by thaJeztah** [comment]
:+1: GitHub has this, I should check, possibly they do it with a bit of CSS `:content` magic
